### ISSUE TITLE
Migrate to embedded-hal 1.0.0

### ISSUE THREAD

**Issue by blaa** [Rahix/port-expander#19]
Hello,
  thanks for the crate. ;-) Just recently played with it and it works nicely. I was going to use it, but then for some other reasons I migrated to embedded-hal 1.0.0 and my OutputPin/InputPin trait integration failed.

I started looking into migrating it to 1.0.0. Maybe it's not that hard, but I don't know if I'll be able to do it so I'll leave a bug. 1.0.0 is pretty recent - only 19 days. But alphas started appearing 2 years ago.

edit: Found a guide: https://github.com/rust-embedded/embedded-hal/blob/master/docs/migrating-from-0.2-to-1.0.md

**Comment by Rahix** [comment]
Ah, please check #16.  It doesn't take care of moving away from `shared-bus` for the mutex abstraction yet, but already implements the e-h 1.0 traits.  So maybe it'll be good enough for your needs for now?

**Comment by blaa** [comment]
I didn't knew immediately, but it's possible (at least with Embassy HAL) to use both embedded-hals at the same time - I've already migrated code to use this approach. Maybe documenting that for less fluent folk would even suffice if you want to stay on 0.2 for a while longer?

```
// cargo.toml:
// embedded-hal = { version = "1.0.0" }
// # Port expander uses 0.2 still.
// embedded-hal-02 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }  

use embedded_hal_02::digital::v2::{
    InputPin,
    OutputPin
};

pub enum UniPin<P>
where
    P: OutputPin + InputPin + Sized
{
    Native(AnyPin),
    Expander(P),
}
```

Kinda what I have now. Migrating obviously will be neater but I see your problem with the Mutex abstraction.
I asked on Embassy group, they've mentioned commonly used `critical_section::Mutex struct` but also that it's difficult to share well a Mutex trait.

If so, maybe doing an own trait and supplying a default Noop implementation would be fine? Or just trying to drop it. Maybe it should be an implementation detail of the Hal implementing the current shared-bus?

**Comment by Rahix** [comment]
> Maybe it should be an implementation detail of the Hal implementing the current shared-bus?

No, a mutex must be supplied by the "OS", not the "hardware".  So the HAL is not the right place to decide on a mutex strategy.  More concretely: Depending on the "OS" you are using (embassy, RTIC, linux, FreeRTOS, etc.), you will need a different mutex type...  The HAL can't and shouldn't be concerned with this.

> they've mentioned commonly used `critical_section::Mutex` struct

This can only be used when using a critical section for all bus interaction is intended.  This may be okay for a lot of projects but isn't favorable for any real-time guarantees you want to uphold.  So it certainly can't be the only solution we support...

> If so, maybe doing an own trait and supplying a default Noop implementation would be fine?

I think this is what we have to do for now...

**Comment by Rahix** [comment]
If anyone here has code using bleeding edge `port-expander` against `embedded-hal` 1.0 traits, please give #26 a try to see if this causes any user-visible breakage (I only care about compilation errors, I do not expect any functional changes from #26)
