### ISSUE TITLE
using Pin as Peripheral/DerefMut

### ISSUE THREAD

**Issue by FrigoEU** [Rahix/port-expander#20]
Hi,

I'm a new Rust developer, trying to use this library to access a pin on a PCA9555 port expander as the RESET pin of an ethernet driver. Even though the Pin struct from this library implements embedded_hal::OutputPin, but it does not implement esp-idf-hal::Peripheral and I don't know how to go forward from here. Is this something that is just not supported by this library? Probably for good reason? Or is there a way to make it work with this library?

In short, I initiatlize my pca9555 and grab the io0_0 pin. This pin is of type 
``` rust 
Pin<Output, NullMutex<Driver<I2cDriver>>>
```

The function I want to pass it to (EthDriver::new_spi) requests the following type: 
```rust 
Option<impl Peripheral<P = impl gpio::OutputPin> + 'd>
```

The compiler gives me the following errors: 
```
the trait bound `port_expander::Pin<'_, port_expander::mode::Output, shared_bus::mutex::NullMutex<port_expander::dev::pca9555::Driver<I2cDriver<'_>>>>: DerefMut` is not satisfied
```

For reference, my full (relevant) code look like this:

``` rust
    let i2cconfig = I2cConfig::new()
        .baudrate(KiloHertz(10).into())
        .sda_enable_pullup(true)
        .scl_enable_pullup(true);

    let i2c_driver_eth = I2cDriver::new(
        peripherals.i2c1,
        peripherals.pins.gpio21,
        peripherals.pins.gpio22,
        &i2cconfig,
    )
    .expect("Failed to create i2c driver");

    let pca9555_eth = port_expander::Pca9555::new(i2c_driver_eth, true, true, true);
    // let boxed_2: Box<port_expander::Pca9555<std::sync::Mutex<_>>> = Box::new(pca9555_2);
    // let never_drop_pca9555_2: &'static mut port_expander::Pca9555<std::sync::Mutex<_>> =
    //     Box::leak(boxed_2);
    // let pca_pins_2 = never_drop_pca9555_2.split();
    let pca_pins_eth = pca9555_eth.split();

    let spidriver = spi::SpiDriver::new(
        peripherals.spi2,
        peripherals.pins.gpio18,       // spi clock
        peripherals.pins.gpio23,       // sdo = mosi = serial data out
        Some(peripherals.pins.gpio19), // sdi = miso = serial data in
        &spi::SpiDriverConfig::new().dma(spi::Dma::Auto(4096)),
    )
    .expect("Failed to make SPI driver");

    let eth_reset_pin = pca_pins_eth
        .io0_0
        .into_output()
        .expect("Failed to grab eth reset pin");

    let ethdriver = eth::EthDriver::new_spi(
        spidriver,
        peripherals.pins.gpio32, // interrupt
        // None as Option<AnyOutputPin>, // cs = chip select
        Some(peripherals.pins.gpio5), // cs = chip select
        // None as Option<AnyOutputPin>, // rst = reset TODO
        Some(eth_reset_pin), // rst = reset,  // !!! THIS LINE PRODUCES THE COMPILER ERROR
        eth::SpiEthChipset::W5500,
        20_u32.MHz().into(),
        None,
        None,
        sysloop.clone(),
    )
    .expect("Failed to make ethernet driver");

```

The line with Some(eth_reset_pin) produces the following compiler error:

```
 main.rs   166   9 error    E0277  the trait bound `port_expander::Pin<'_, port_expander::mode::Output, shared_bus::mutex::NullMutex<port_expander::dev::pca9555::Driver<I2cDriver<'_>>>>: DerefMut` is not satisfied
 the following other types implement trait `Peripheral`:
   AnyIOPin
   AnyInputPin
   AnyOutputPin
   Modem
   ADC1
   ADC2
   CAN
   Gpio0
 and 78 others
 required for `port_expander::Pin<'_, port_expander::mode::Output, shared_bus::mutex::NullMutex<port_expander::dev::pca9555::Driver<I2cDriver<'_>>>>` to implement `Peripheral` (lsp)
```

This is the signature of new_spi:

``` rust
    pub fn new_spi(
        driver: T,
        int: impl Peripheral<P = impl gpio::InputPin> + 'd,
        cs: Option<impl Peripheral<P = impl gpio::OutputPin> + 'd>,
        rst: Option<impl Peripheral<P = impl gpio::OutputPin> + 'd>,
        chipset: SpiEthChipset,
        baudrate: Hertz,
        mac_addr: Option<&[u8; 6]>,
        phy_addr: Option<u32>,
        sysloop: EspSystemEventLoop,
    ) -> Result<Self, EspError>
```

I'm kind of stuck here and not sure what to do from here. If I need to provide any more information, please let me know.

Thanks already for any help!

**Comment by FrigoEU** [comment]
I've now also tried the "newtype" approach as follows:

`` rust
pub struct MyPin<'a, MODE, MUTEX> {
    pin: port_expander::Pin<'a, MODE, MUTEX>,
}

impl<'a, MODE, MUTEX> Deref for MyPin<'a, MODE, MUTEX> {
    type Target = port_expander::Pin<'a, MODE, MUTEX>;

    fn deref(&self) -> &Self::Target {
        &self.pin
    }
}

impl<'a, MODE, MUTEX> DerefMut for MyPin<'a, MODE, MUTEX> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.pin
    }
}

    let eth_reset_pin = MyPin {
        pin: pca_pins_eth
            .io0_0
            .into_output()
            .expect("Failed to grab ethernet reset pin"),
    };
```

But I get the same error :(.

**Comment by FrigoEU** [comment]
I forgot to mention that all of this is in cooperation with the esp-idf-* libraries, eg the Peripheral type: https://github.com/esp-rs/esp-idf-hal/blob/1bbda8170501beb46e65095cb91f6be54f699a20/src/peripheral.rs

**Comment by Rahix** [comment]
Hi,

the problem is that `esp-idf-svc` isn't flexible enough to take an arbitrary "pin" as a reset pin.  As you correctly identified, `EthDriver::new()` requires an `OutputPin` peripheral:

https://github.com/esp-rs/esp-idf-svc/blob/2e7806d6c91961f47b8b6efdd0466e28a830db58/src/eth.rs#L199

And `OutputPin` is an internal concept to `esp-idf-hal`:

https://github.com/esp-rs/esp-idf-hal/blob/master/src/gpio.rs#L30

There is no way for you to implement this trait because a port-expander pin can never be turned into a pin of the ESP.

Fixing this is only really possible by making `esp-idf-svc` take an arbitrary `embedded-hal` `OutputPin` as the reset pin.  But at first glance, that looks difficult to do because the reset pin is actually passed really deep into the inner workings:

https://github.com/esp-rs/esp-idf-svc/blob/2e7806d6c91961f47b8b6efdd0466e28a830db58/src/eth.rs#L768

**Comment by FrigoEU** [comment]
Hey Rahix,

Thanks a lot for the explanation, that does make sense. The incompatibility is unfortunate! Though I understand there is nothing this package can do to improve it.

Luckily in this case, I've managed to get the ethernet chip working without the reset pin. I'm just doing a manual reset at the start of my program.

Thanks again!
