### ISSUE TITLE
PortDriverTotemPole trait bound for OutputPin trait when using PCF8574/8575 not satisfied

### ISSUE THREAD

**Issue by tomried** [Rahix/port-expander#33]
Hi,
I'm trying to update a library which depends on this crate (ag-lcd) to embedded-hal 1.0.0. 
It currently uses version 0.3.1 of port-expander, before the PortDriverTotemPole trait bound was introduced for the OutputPin.
In the current version, this trait bound is present, but the trait is not implemented for PCF8574/8575, which leads to following error when trying to use port-expander with an OutputPin:
```
the trait `port_expander::common::PortDriverTotemPole` is not implemented for `port_expander::dev::pcf8574::Driver<I2C>`, which is required by `port_expander::Pin<'_, QuasiBidirectional, M>: OutputPin`
```

The bound seems to be necessary, as removing it from OutputPin causes another error:
```
the trait `PortDriverTotemPole` is not implemented for `PD`, which is required by `pin::Pin<'a, MODE, MUTEX>: embedded_hal::digital::ErrorType`
```
Is the solution to this problem to implement the PortDriverTotemPole trait for pcf8574/pcf8575? I'm not sure how the implementation should look like, could you please help me?

**Comment by Rahix** [comment]
Release 0.6.2 (and 0.5.1) with the fix for this regression :)
